### ISSUE TITLE
Doesn't work with plugin org.kde.slideshow

### ISSUE THREAD

**Issue by Vasqs** [luisbocanegra/kde-material-you-colors#12]
The wallpaper goes blinking and changing often

**Comment by luisbocanegra** [comment]
That's because (as far as I know) slideshow wallpapers cannot be obtained with the same dbus call, like static wallpapers do, it runs a [script](https://github.com/luisbocanegra/kde-material-you-colors/blob/0a9a347b7c8e69eb02e408cdc0d998f9c7ed193b/kde-material-you-colors.py#L45) to obtain the wallpaper from plasmashell, or maybe the configuration is different and it can be obtained but reading a different config.

I did something like this from [latte_slideshow_wallpaper](https://github.com/psifidotos/latte_slideshow_wallpaper/blob/master/contents/ui/LatteTracer.qml#L69) for the plugin [Inactive Blur](https://github.com/Zren/plasma-wallpapers/tree/master/inactiveblur), but making it write the current wallpaper path every update to a /tmp file and used that to get colors.

**Comment by luisbocanegra** [comment]
You  can try [my fork ](https://github.com/luisbocanegra/ksetwallpaper) of pashazz [ksetwallpaper](https://github.com/pashazz/ksetwallpaper) as a workaround for now. I added a slideshow like feature that cycles randomly through images of a folder and applies it to all screens in a specified amount of time.

**Comment by luisbocanegra** [comment]
Okay, after some testing I can say that it _should_ work with org.kde.slideshow, you say the wallpaper goes blinking,but colors doesnt change? Could it be that you were runing it twice (with the startup service and terminal)?

**Comment by luisbocanegra** [comment]
Closing this now, but you can still comment, if the problem persists I'll reopen it.
