### ISSUE TITLE
Desktop entries doesn't seem to launch script

### ISSUE THREAD

**Issue by ShatteredSkies** [luisbocanegra/kde-material-you-colors#129]
**Describe the bug**
on v1.5.0:
desktop entries for kde-material-you-colors doesn't seem to do anything, breaking autostart.

**Additional context**
installed from the AUR.
launching `kde-material-you-colors` from the terminal does work.

**Comment by luisbocanegra** [comment]
Just tried, yes it doesn't run 👎  but found out why. It's the formatting for the argument parser (used to make `--help` wider), it tries to get the terminal size `stty size` but fails since it's not available when running from a desktop entry (non-interactive mode). I think I'll just add an exception since `--help` should be ran from interactive terminals anyway.

Thanks for reporting it.

**Comment by luisbocanegra** [comment]
Should be fixed in https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v1.5.1
