### ISSUE TITLE
[Feedback needed] How to automatically enable on konsole?

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/kde-material-you-colors#156]
https://github.com/luisbocanegra/kde-material-you-colors/assets/17055027/a93f6d02-9ee3-476e-a143-4b1d0a3a62d4

I have everytime to manually type the command in each of konsole's tab for each to work?

And if i press Ctrl+C it stops when i change the wallpapers.

How is that?

**Comment by luisbocanegra** [comment]
You need to create a new Konsole profile, set it as default and pass its name in the command or config file (it's easier to use the Plasmoid for the last).

You will need to edit the new Konsole profile and manually set any color scheme, then after running `kde-material-you-colors` again you should see the color scheme change for all Konsole instances

The reason a Konsole profile is needed  (actually two profiles) is because Konsole doesn't update colors when setting the same color scheme repeatedly even when it has different colors, same applies to profiles, so there needs to be two profiles with two different color schemes, the current and the new one, when the color scheme changes it detects which profile is on which Konsole instance and switches to the other.

**Comment by luisbocanegra** [comment]
> And if i press Ctrl+C it stops when i change the wallpapers.
> 
> How is that?

That's probably because the signal kills a sub process instead of the main one, this probably can be fixed but is low priority, if you want to kill the background process for sure use `kde-material-you-colors --stop`

**Comment by luisbocanegra** [comment]
After the changes in https://github.com/luisbocanegra/kde-material-you-colors/commit/92bc81db44396835595382a11c2112e2a32ff664 and https://github.com/luisbocanegra/kde-material-you-colors/pull/167 setting a profile (or even having profiles at all) will no longer be necessary if a default is found it will be themed, if there is no default it creates `Profile 1` themes and makes it the default.

Note that after running `kde-material-you-colors` for the first time if konsole is open is still needed to start a new window so changes show in all splits/tabs.

To test: 

Rename `~/.config/konsolerc` and `~/.local/share/konsole/`

Open a new konsole window (should have the default theme)

Then clone and run the main branch:
```
git clone https://github.com/luisbocanegra/kde-material-you-colors
export PYTHONPATH=/home/luis/projects/kde-material-you-colors/src:$PYTHONPATH
python -m kde_material_you_colors.main
```
There should be no errors and launching a new window will show the correct colors

Finally, restore  `~/.config/konsolerc` and `~/.local/share/konsole/` back to the originals
