### ISSUE TITLE
FYI, A working OpenSUSE Tumbleweed package 

### ISSUE THREAD

**Issue by pallaswept** [luisbocanegra/kde-material-you-colors#195]
https://build.opensuse.org/package/show/home:kingy:branches:home:pallaswept:branches:luisbocanegra/kde-material-you-colors

A mate asked me if I had any idea why he might be unable to build the backend, as the build was generating errors. I figured, if I'm going to troubleshoot the build, might as well do it in a package, and then it's repeatable :)

I used an existing package as a starting point, and just updated it to a recent version, and fixed a few glitches that were causing it to fail. So really, I didn't create the package, I just fixed and updated it. Credit to the original author, here!

My mate found a few missing packages that caused the script to fail at first, so he added those to the recommends, afterwards.

Between the three of us, we have a working OpenSUSE package here. It almost certainly needs some polish before widespread use, but it definitely functions as expected.

Perhaps it's helpful to you? I'll close this issue now, just wanted to let you know.

**Comment by luisbocanegra** [comment]
Hi, I will take a look and try that package this weekend and possibly add it here https://build.opensuse.org/package/show/home:luisbocanegra/kde-material-you-colors if I have the time. 

Thank you.

**Comment by luisbocanegra** [comment]
I added it to my project and is building correctly, but have a couple of questions

Currently, it provides multiple packages for different python versions, according to OpenSUSE spec documentation that is only required for packages that are meant to be used as modules, should I lock the package to the latest python version instead? I already removed the python- prefix because it can be executed as separate program and will later install the start/stop desktop entries.

Also, since there is a C++ Kwin plugin (for taking screenshots) and a Plasmoid going the multiple python versions way doesn't allow shipping extra files that go in /usr, so for now I made a separate package that installs that.

I would prefer it to be a single package, hence the question about locking to a latest python version, what do you think about this? I never used OpenSUSE or OBS until yesterday

**Comment by luisbocanegra** [comment]
Update: Went the single python version way, now backend + screenshot helper + widget are installed with a single package [kde-material-you-colors](https://build.opensuse.org/package/show/home:luisbocanegra/kde-material-you-colors), just Tumbleweed for now but will add more distros hopefully before releasing the next version.

Thanks for the help!

**Comment by pallaswept** [comment]
Nice! Mate, this thing is so pretty. Plasma is amazing but you just put the icing on the cake.
