### ISSUE TITLE
icon set isn't found

### ISSUE THREAD

**Issue by chrostino** [luisbocanegra/kde-material-you-colors#212]
**Describe the bug**
I have two icon set installed: Tela and Qogir, but Tela is listed in the widget advanced settings (together with Breeze) while Qogir no
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/100096435/7e119aba-a215-4fd0-9d41-784417e310b8)

Also some programs like spotify or vscode don't get themed as shown in the example

**Desktop**
 - Operating System: Fedora 40
 - KDE Plasma Version: 6.0.5
 - KDE Frameworks Version: 6.3.0
 - Qt Version: 6.7.1
 - Graphics Platform: Wayland
 - Things in your system that might be relevant: none

**Comment by luisbocanegra** [comment]
This is because that icon theme also includes cursors. In the widget ([FullRepresentation.qml#L91](https://github.com/luisbocanegra/kde-material-you-colors/blob/a59a61a4bd1c569ed943c4e7ad77b408a7eb68da/src/plasmoid/package/contents/ui/FullRepresentation.qml#L91)) I use the command bellow to get the icons but since I was also getting cursor themes I filtered them out.

```sh
find /usr/share/icons ~/.local/share/icons -maxdepth 2 -type f -path '*/icons/*/index.theme' ! -path '*/share/icons' ! -exec grep -q '^Hidden=true' {} \; ! -execdir test -d cursors \; -printf '%p\n' | while read line; do echo "$(basename $(dirname $line)),$(grep '^Name=' $line | sed 's/^Name=//')"; done
```

I will replace that with this one. Can you confirm it works?

```
find /usr/share/icons ~/.local/share/icons -maxdepth 1 -type d -exec test -f "{}/index.theme" \; ! -exec grep -q '^Hidden=true' {}/index.theme \; -exec sh -c 'test "$(find "$1" -maxdepth 1 -type d | wc -l)" -gt 2' _ {} \; -printf '%p\n' | while read line; do echo "$(basename $line),$(grep '^Name=' $line/index.theme | sed 's/^Name=//')"; done | sort --field-separator=, --key=2n -k2,2
```

In the widget would be `property string getIconThemesCommand: "find /usr/share/icons " +homeDir+"/.local/share/icons -maxdepth 1 -type d -exec test -f \"{}/index.theme\" \\; ! -exec grep -q '^Hidden=true' {}/index.theme \\; -exec sh -c 'test \"$(find \"$1\" -maxdepth 1 -type d | wc -l)\" -gt 2' _ {} \\; -printf '%p\\n' | while read line; do echo \"$(basename $line),$(grep '^Name=' $line/index.theme | sed 's/^Name=//')\"; done | sort --field-separator=, --key=2n -k2,2"`

I think it would be better to either make it a separate shell script or move that to the backend but that should do for now

**Comment by luisbocanegra** [comment]
> Also some programs like spotify or vscode don't get themed as shown in the example

Vscode requires pywal + https://github.com/dlasagno/vscode-wal-theme, spotify requires spicetify + a configuration that loads colors from either pywal cache or the json. In the screenshots I  was using this theme I made https://github.com/luisbocanegra/spicetify-kde-material-you but kinda lost interest on fixing it after every update

**Comment by chrostino** [comment]
> I will replace that with this one. Can you confirm it works?
```
find /usr/share/icons ~/.local/share/icons -maxdepth 1 -type d -exec test -f "{}/index.theme" \; ! -exec grep -q '^Hidden=true' {}/index.theme \; -exec sh -c 'test "$(find "$1" -maxdepth 1 -type d | wc -l)" -gt 2' _ {} \; -printf '%p\n' | while read line; do echo "$(basename $line),$(grep '^Name=' $line/index.theme | sed 's/^Name=//')"; done | sort --field-separator=, --key=2n -k2,2
```
works like a charm
