### ISSUE TITLE
folder icons in some some icon packs don't get themed in the file explorer

### ISSUE THREAD

**Issue by chrostino** [luisbocanegra/kde-material-you-colors#218]
**Describe the bug**
When I open dolphin with tela set as icons, the folder icons match the color accent, while with the qogir icons it doesn't

**Expected behavior**
folder icons from any pack get themed

**Screenshots**
Tela
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/100096435/ed929050-96d2-498a-8b8d-1b9b1a1e9891)

Qogir
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/100096435/bc806455-8364-45f1-b3fa-b1d14b454ea4)

**Desktop (please complete the following information):**
 - Operating System: Fedora 40
 - KDE Plasma Version: 6.1.1
 - KDE Frameworks Version: 6.3.0
 - Qt Version: 6.7.1
 - Graphics Platform: Wayland
 - Things in your system that might be relevant: none

**Comment by luisbocanegra** [comment]
To change with accent color the icons need to support it https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips

Examples of this are [Breeze Icons](https://invent.kde.org/frameworks/breeze-icons) and [Papirus Colors](https://github.com/varlesh/papirus-colors). Also, since most icons expect pale colors, I have a patched version of these icons to look well with kde-material-you-colors [breeze-folder-icons-patcher](https://github.com/luisbocanegra/breeze-folder-icons-patcher) and [patched papirus-colors](https://github.com/luisbocanegra/papirus-colors) respectively.

There is also a tool that can recolor icons https://github.com/NicklasVraa/Color-manager maybe you can configure it in a way to only change the folder color (current colors are saved to /tmp/kde-material-you-colors-luis.json)

If you don't intend to change colors very often you may also put your script in advanced settings so colors are applied when you change the colors
