### ISSUE TITLE
Folder icons not looking right

### ISSUE THREAD

**Issue by Prayag2** [luisbocanegra/kde-material-you-colors#26]
Folder icons in Dolphin don't look quite right. Here are some screenshots:

On dark themes
![image](https://user-images.githubusercontent.com/39525869/162393803-e717bf91-d1fa-4b9c-b5e5-4d43fab9ea5f.png)

On light themes
![image](https://user-images.githubusercontent.com/39525869/162393882-a8ff66ca-4c55-4be9-9cab-0046511e5774.png)

The colour of the emblems should be dark when the folder colour is light and light when the folder colour is dark.

**Comment by luisbocanegra** [comment]
Have you tried using the new option to switch between icon themes? It was added in the latest version.
Can you also share how does it look with the default breeze dark and light themes? Never noticed this because I always use Papirus icons, and checking right now it seems like my dolphin is a bit buggy as selecting makes the folders all white.

**Comment by Prayag2** [comment]
Default Breeze Dark:
![image](https://user-images.githubusercontent.com/39525869/162400181-d8ff1f97-5549-4e67-954f-673764ad7e94.png)

Default Breeze Light:
![image](https://user-images.githubusercontent.com/39525869/162400161-d0bf448e-cdaf-405c-b121-45d28c3b375e.png)


ohh it's working fine with `kde-material-you-colors --iconslight ICONSLIGHT`
![image](https://user-images.githubusercontent.com/39525869/162400597-f5efbb47-c01e-4394-a2ef-ce879ff8119d.png)

**Comment by luisbocanegra** [comment]
Thanks.
> ohh it's working fine with `kde-material-you-colors --iconslight ICONSLIGHT`

Are you running it exactly like that? Probably not but just to be sure, you have to pass after --iconslight the name of one of the installed icon themes.

**Comment by Prayag2** [comment]
Yes, I'm running that exactly like that lol

**Comment by Prayag2** [comment]
I made a mistake!! I was using a custom accent colour that's why it was working :( When using the accent colour of the colour scheme, it's still not working:
![image](https://user-images.githubusercontent.com/39525869/162404103-25bcca0a-71c0-4e3d-94d8-ac9b4550fe60.png)

**Comment by luisbocanegra** [comment]
Okay, I will check this later, thanks for reporting it.

**Comment by luisbocanegra** [comment]
Update, tried reducing the tint of folders background with
```
[Colors:Selection]
BackgroundNormal=
```
until icons were readable, but didn't like the result as it also affected other elements that looked right otherwise :-1: 


For the folder icons, Breeze uses window text color, which is almost black (light theme) or white (dark theme)
```
[Colors:Window]
ForegroundNormal=
```
![Screenshot_20220410_123322_Home](https://user-images.githubusercontent.com/15076387/162631962-bd4ea9dc-e03a-4861-a788-dd284ca0a2c8.png)

I think this is more of a conflict with the default colors for the breeze icon theme, I don't know why they didn't use 
```
[Colors:Selection]
ForegroundNormal=
```
![image](https://user-images.githubusercontent.com/15076387/162632877-09c94eec-762b-44e8-94ad-f779a948d616.png)

Maybe there are other parts of the ui that depend on the same colors and causes readability issues somewhere, so I don't think I can solve this one without sacrificing consistency. Or changing all the icons afected by this manually
Maybe it would be worth asking the KDE VDG group what do they think about this but idk.

Please leave this open for now.

**Comment by luisbocanegra** [comment]
Just an update on this issue, I use the `Papirus-Colors`, icons they follow the current color scheme and had this same issue.

I patched those icons replacing the css class in some elements and it seems to have worked perfectly. 

If someone also uses the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) you can get the patched version if `Papirus-Colors` from [my fork](https://github.com/luisbocanegra/papirus-colors)

Install both `Papirus icon theme` and  `Papirus-Colors` and apply `Papirus-Colors` in system settings

**Comment by luisbocanegra** [comment]
I've now made a script to patch breeze folder icons too, if anyone wants can get it [here](https://github.com/luisbocanegra/breeze-folder-icons-patcher)

## Before:
![breeze-before](https://user-images.githubusercontent.com/15076387/208795412-687c06a3-ed53-46b4-8ae0-fc0da2062ad4.png)

## After
![breeze-after](https://user-images.githubusercontent.com/15076387/208795462-2c645034-d6c4-48a4-a111-c711cc78f3b7.png)
