### ISSUE TITLE
Integrate pywal.

### ISSUE THREAD

**Issue by Casul51** [luisbocanegra/kde-material-you-colors#27]
Since you have already working plasma's wallpaper change trigger, it would be cool if you implement invoking [pywal](https://github.com/dylanaraps/pywal) with wallpaper change or support executing custom shell commands.

**Comment by luisbocanegra** [comment]
Never used pywal, but with a quick glance I see it supports theming for a lot of programs by generating its own color schemes, that's very cool, but what could be even cooler would be integrating it into kde-material-you-colors and replacing those [generated colors](https://github.com/dylanaraps/pywal/blob/236aa48e741ff8d65c4c3826db2813bf2ee6f352/pywal/colors.py#L30) with material you based ones.

Also I think this could be two separate feature requests (issues), right? One for pywal integration (because it will need the wallpaper path to work) and other for executing custom shell commands.

**Comment by Casul51** [comment]
For executing custom shell commands I believe would be good to provide wallpaper path in variable.

> replacing those [generated colors](https://github.com/dylanaraps/pywal/blob/236aa48e741ff8d65c4c3826db2813bf2ee6f352/pywal/colors.py#L30) with material you based ones, that would be super cool.

Yep, thou I believe it need to be checked, since those colors are going to be used primary in terminal, so if will be readable It definitely will be cool.

> Also I think this could be two separate feature requests (issues), right?

Yep, reasonable enough.

**Comment by luisbocanegra** [comment]
Added in [v0.4.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.4.0BETA) please test it and give feedback
![09](https://user-images.githubusercontent.com/15076387/163057947-547d964e-7e5d-4672-ab61-9fed964d22cf.png)
.
