### ISSUE TITLE
[Feedback needed] Support for Dynamic wallpaper plugin

### ISSUE THREAD

**Issue by l0drex** [luisbocanegra/kde-material-you-colors#40]
Crashes when using [dynamic wallpapers](https://github.com/zzag/plasma5-wallpapers-dynamic):

```
ERROR:dbus.proxies:Introspect error on :1.22:/PlasmaShell: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Error getting wallpaper from dbus:
org.freedesktop.DBus.Error.ServiceUnknown: The name :1.22 was not provided by any .service files
^CTraceback (most recent call last):
  File "/usr/lib/kde-material-you-colors/kde-material-you-colors.py", line 508, in <module>
    time.sleep(1)
```

**Comment by luisbocanegra** [comment]
This is because Dynamic wallpapers uses a special image format (AVIF) that isn't unpacked anywhere I think, if it does (e.g. cache) then we could use that. If not maybe it's worth asking them to implement it as a feature if it's possible. 

Other could be figuring a way to open that file within pyhton and extracting the frame but I don't even know if that's possible.

**Comment by luisbocanegra** [comment]
Support for all types of wallpapers has been added in main branch, it works by taking a screenshot of the desktop window.

To test:
```
git clone https://github.com/luisbocanegra/kde-material-you-colors
export PYTHONPATH=/home/luis/projects/kde-material-you-colors/src:$PYTHONPATH
python -m kde_material_you_colors.main
```

**Comment by luisbocanegra** [comment]
Also see https://github.com/luisbocanegra/kde-material-you-colors/issues/163#issuecomment-1850994337
