### ISSUE TITLE
Dynamically update Konsole color scheme

### ISSUE THREAD

**Issue by throwaway69420-69420** [luisbocanegra/kde-material-you-colors#43]

**Comment by luisbocanegra** [comment]
Currently, thanks to pywal they are updated on wallpaper/light/dark change, the problem is that Konsole doesn't "watch" the color scheme file for changes. This is why you have to start a new Konsole instance to see updated colors. 
Maybe there is a way to reload the Konsole color scheme but I don't know.

**Comment by throwaway69420-69420** [comment]
I don't know much about pywal, can pywal also change the kde color scheme?

**Comment by luisbocanegra** [comment]
> I don't know much about pywal, can pywal also change the kde color scheme?

No, at least by itself it can't, unless someone made a plugin that reads the color palette from pywal and applies it to Plasma.

I could've used pywal but I liked Material You more since it has the advantage of a ready to use color palette, but I still use the power of pywal (to theme other apps like terminals) but passing material you colors to it.

**Comment by throwaway69420-69420** [comment]
I will try pywall today for Konsole color scheme

**Comment by throwaway69420-69420** [comment]
hello, I need some help
I am on arch linux and have installed pywal through pacman https://archlinux.org/packages/community/any/python-pywal/

will this work or do I need to install it through pip?

**Comment by throwaway69420-69420** [comment]
update: the pacman page of pywal works well

**Comment by tuhanayim** [comment]
You need to add `-wal` flag for enabling pywal generating and `-wald` or `-wall` for dark or light scheme generation. After that, [you need to link pywal's konsole theme to `.local/share/konsole` folder](https://github.com/dylanaraps/pywal/wiki/Customization#konsole=). But as @luisbocanegra said, on every scheme change, you need to restart *(or re-apply pywal's konsole theme from settings)* in order to reflecting changes.

**Comment by throwaway69420-69420** [comment]
hello @tuhanayim 
I have done it, it works now

**Comment by luisbocanegra** [comment]
Managed to get Konsole to reload color schemes on all opened instances (mostly) by switching profiles :tada:. If someone wants to try check configuration template in dev branch for instructions.

https://user-images.githubusercontent.com/15076387/164975894-1b045e94-11b2-41e2-aa5e-4d65aff6d9bb.mp4

**Comment by tuhanayim** [comment]
It works as expected for me. *But at first wallpaper change, it selected blue as a main color but the wallpaper is black&white :thinking: I tested and it uses blue as accent color on all wallpapers use black&white colors heavily.*

https://user-images.githubusercontent.com/83988414/164981362-c98885d2-76df-4661-9c54-0f9b20a5e423.mp4

**Comment by luisbocanegra** [comment]
> It works as expected for me. 

Thank you.
> _But at first wallpaper change, it selected blue as a main color but the wallpaper is black&white thinking I tested and it uses blue as accent color on all wallpapers use black&white colors heavily._

That's how  [MaterialColorUtilities](https://github.com/albi005/MaterialColorUtilities) work, if doesn't find a _suitable_ color a default predefined fallback one is used, which happens to be the blue you see. Maybe it can be modified to allow more grayish colors, will check what later.

**Comment by luisbocanegra** [comment]
Added in  [v0.6.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.6.0BETA)
