### ISSUE TITLE
Don't work with manually selected file. UnicodeDecodeError

### ISSUE THREAD

**Issue by Casul51** [luisbocanegra/kde-material-you-colors#6]
```
kde-material-you-colors --file "/home/casual/Pictures/wallpaper14504.jpeg"

Current config: Plugin: org.kde.image | Light mode: None | File: /home/casual/Pictures/wallpaper14504.jpeg | Monitor: 0
Traceback (most recent call last):
File "/usr/lib/kde-material-you-colors/kde-material-you-colors.py", line 225, in <module>
wallpaper_old = currentWallpaper(options_old)
File "/usr/lib/kde-material-you-colors/kde-material-you-colors.py", line 192, in currentWallpaper
return get_wallpaper_path(plugin=options['plugin'], monitor=options['monitor'], file=options['file'])
File "/usr/lib/kde-material-you-colors/kde-material-you-colors.py", line 28, in get_wallpaper_path
wallpaper = str(file.read()).replace('file://', '').strip()
File "/usr/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
Same issue with any other image thou works without choosing file.

Operating System: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.15-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
You're getting this error because the `--file` flag takes a text file containing the absolute path of an image, I realized too late that this would be confusing and was planning to add `--image`, or maybe merging them together and checking if the passed file is an image.

The reason I did it like that is because on Plasma slideshow plugins (AFAIK) don't expose the current wallpaper. I did something like this from [latte_slideshow_wallpaper](https://github.com/psifidotos/latte_slideshow_wallpaper/blob/master/contents/ui/LatteTracer.qml#L69) for the plugin [Inactive Blur](https://github.com/Zren/plasma-wallpapers/tree/master/inactiveblur), but making it write the current wallpaper path every update to a /tmp file and used that to get colors.

**Comment by Casul51** [comment]
Wow, that is really confusing. 
_Yep, that's how programming works._ :)
